<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class jugadoresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $jugadores = [
            [
                'nombre' => 'Devin Booker',
                'equipo' => 'Phoenix Suns',
                'posicion' => 'Escolta',
                'rareza' => 91,
                'tiro' => 85,
                'defensa' => 80,
                'asistencias' => 75,
                'rebotes' => 70,
                'atletismo' => 75,
                'foto' => 'devin_booker.jpg',
                'precio' => 110,
            ],
            [
                'nombre' => 'LeBron James',
                'equipo' => 'Los Angeles Lakers',
                'posicion' => 'Alero',
                'rareza' => 100,
                'tiro' => 90,
                'defensa' => 90,
                'asistencias' => 92,
                'rebotes' => 90,
                'atletismo' => 95,
                'foto' => 'lebron_james.jpg',
                'precio' => 200,
            ],
            [
                'nombre' => 'Luka Dončić',
                'equipo' => 'Dallas Mavericks',
                'posicion' => 'Base',
                'rareza' => 96,
                'tiro' => 88,
                'defensa' => 85,
                'asistencias' => 88,
                'rebotes' => 82,
                'atletismo' => 85,
                'foto' => 'luka_doncic.jpg',
                'precio' => 160,
            ],
            [
                'nombre' => 'Kevin Durant',
                'equipo' => 'Phoenix Suns',
                'posicion' => 'Alero',
                'rareza' => 97,
                'tiro' => 90,
                'defensa' => 87,
                'asistencias' => 86,
                'rebotes' => 85,
                'atletismo' => 90,
                'foto' => 'kevin_durant.jpg',
                'precio' => 170,
            ],
            [
                'nombre' => 'Stephen Curry',
                'equipo' => 'Golden State Warriors',
                'posicion' => 'Base',
                'rareza' => 97,
                'tiro' => 92,
                'defensa' => 80,
                'asistencias' => 88,
                'rebotes' => 75,
                'atletismo' => 85,
                'foto' => 'stephen_curry.jpg',
                'precio' => 170,
            ],
            [
                'nombre' => 'Giannis Antetokounmpo',
                'equipo' => 'Milwaukee Bucks',
                'posicion' => 'Alero',
                'rareza' => 100,
                'tiro' => 85,
                'defensa' => 95,
                'asistencias' => 88,
                'rebotes' => 95,
                'atletismo' => 98,
                'foto' => 'giannis_antetokounmpo.jpg',
                'precio' => 200,
            ],
            [
                'nombre' => 'James Harden',
                'equipo' => 'Philadelphia 76ers',
                'posicion' => 'Escolta',
                'rareza' => 95,
                'tiro' => 88,
                'defensa' => 78,
                'asistencias' => 85,
                'rebotes' => 75,
                'atletismo' => 80,
                'foto' => 'james_harden.jpg',
                'precio' => 150,
            ],
            [
                'nombre' => 'Kawhi Leonard',
                'equipo' => 'Los Angeles Clippers',
                'posicion' => 'Alero',
                'rareza' => 96,
                'tiro' => 86,
                'defensa' => 92,
                'asistencias' => 80,
                'rebotes' => 82,
                'atletismo' => 85,
                'foto' => 'kawhi_leonard.jpg',
                'precio' => 160,
            ],
            [
                'nombre' => 'Nikola Jokić',
                'equipo' => 'Denver Nuggets',
                'posicion' => 'Pivot',
                'rareza' => 98,
                'tiro' => 88,
                'defensa' => 87,
                'asistencias' => 90,
                'rebotes' => 85,
                'atletismo' => 85,
                'foto' => 'nikola_jokic.jpg',
                'precio' => 180,
            ],
            [
                'nombre' => 'Joel Embiid',
                'equipo' => 'Philadelphia 76ers',
                'posicion' => 'Pivot',
                'rareza' => 96,
                'tiro' => 85,
                'defensa' => 88,
                'asistencias' => 78,
                'rebotes' => 85,
                'atletismo' => 82,
                'foto' => 'joel_embiid.jpg',
                'precio' => 160,
            ],
            [
                'nombre' => 'Anthony Davis',
                'equipo' => 'Los Angeles Lakers',
                'posicion' => 'Ala-pivot',
                'rareza' => 96,
                'tiro' => 85,
                'defensa' => 90,
                'asistencias' => 80,
                'rebotes' => 85,
                'atletismo' => 86,
                'foto' => 'anthony_davis.jpg',
                'precio' => 160,
            ],
            [
                'nombre' => 'Damian Lillard',
                'equipo' => 'Milwaukee Bucks',
                'posicion' => 'Base',
                'rareza' => 94,
                'tiro' => 88,
                'defensa' => 78,
                'asistencias' => 80,
                'rebotes' => 70,
                'atletismo' => 75,
                'foto' => 'damian_lillard.jpg',
                'precio' => 140,
            ],
            [
                'nombre' => 'Jimmy Butler',
                'equipo' => 'Miami Heat',
                'posicion' => 'Alero',
                'rareza' => 94,
                'tiro' => 85,
                'defensa' => 85,
                'asistencias' => 80,
                'rebotes' => 75,
                'atletismo' => 75,
                'foto' => 'jimmy_butler.jpg',
                'precio' => 140,
            ],
            [
                'nombre' => 'Kyrie Irving',
                'equipo' => 'Dallas Mavericks',
                'posicion' => 'Base',
                'rareza' => 95,
                'tiro' => 88,
                'defensa' => 75,
                'asistencias' => 80,
                'rebotes' => 70,
                'atletismo' => 75,
                'foto' => 'kyrie_irving.jpg',
                'precio' => 150,
            ],
            [
                'nombre' => 'Jayson Tatum',
                'equipo' => 'Boston Celtics',
                'posicion' => 'Alero',
                'rareza' => 93,
                'tiro' => 86,
                'defensa' => 80,
                'asistencias' => 78,
                'rebotes' => 75,
                'atletismo' => 74,
                'foto' => 'jayson_tatum.jpg',
                'precio' => 130,
            ],
            [
                'nombre' => 'Bradley Beal',
                'equipo' => 'Phoenix Suns',
                'posicion' => 'Escolta',
                'rareza' => 93,
                'tiro' => 87,
                'defensa' => 75,
                'asistencias' => 78,
                'rebotes' => 75,
                'atletismo' => 75,
                'foto' => 'bradley_beal.jpg',
                'precio' => 130,
            ],
            [
                'nombre' => 'Donovan Mitchell',
                'equipo' => 'Cleveland Cavaliers',
                'posicion' => 'Escolta',
                'rareza' => 92,
                'tiro' => 85,
                'defensa' => 75,
                'asistencias' => 75,
                'rebotes' => 70,
                'atletismo' => 75,
                'foto' => 'donovan_mitchell.jpg',
                'precio' => 120,
            ],
            [
                'nombre' => 'Paul George',
                'equipo' => 'Los Angeles Clippers',
                'posicion' => 'Alero',
                'rareza' => 92,
                'tiro' => 84,
                'defensa' => 85,
                'asistencias' => 78,
                'rebotes' => 74,
                'atletismo' => 75,
                'foto' => 'paul_george.jpg',
                'precio' => 120,
            ],
            [
                'nombre' => 'Chris Paul',
                'equipo' => 'Golden State Warriors',
                'posicion' => 'Base',
                'rareza' => 91,
                'tiro' => 84,
                'defensa' => 80,
                'asistencias' => 88,
                'rebotes' => 70,
                'atletismo' => 75,
                'foto' => 'chris_paul.jpg',
                'precio' => 110,
            ],
            [
                'nombre' => 'Zion Williamson',
                'equipo' => 'New Orleans Pelicans',
                'posicion' => 'Ala-pivot',
                'rareza' => 95,
                'tiro' => 86,
                'defensa' => 80,
                'asistencias' => 80,
                'rebotes' => 75,
                'atletismo' => 85,
                'foto' => 'zion_williamson.jpg',
                'precio' => 150,
            ],
            [
                'nombre' => 'Trae Young',
                'equipo' => 'Atlanta Hawks',
                'posicion' => 'Base',
                'rareza' => 91,
                'tiro' => 84,
                'defensa' => 70,
                'asistencias' => 82,
                'rebotes' => 70,
                'atletismo' => 74,
                'foto' => 'trae_young.jpg',
                'precio' => 110,
            ],
            [
                'nombre' => 'Bam Adebayo',
                'equipo' => 'Miami Heat',
                'posicion' => 'Pivot',
                'rareza' => 90,
                'tiro' => 80,
                'defensa' => 85,
                'asistencias' => 75,
                'rebotes' => 80,
                'atletismo' => 80,
                'foto' => 'bam_adebayo.jpg',
                'precio' => 100,
            ],
        ];

        foreach ($jugadores as &$jugador) {
            $jugador['created_at'] = now();
            $jugador['updated_at'] = now();
        }

        DB::table('jugadores')->insert($jugadores);
    
    }
}
